<template>

</template>

<script>
export default {
  data () {
    return {
      icons: [
        'assignment',
        'assessment',
        'aspect ratio',
        'announcement',
        'android',
        'all out',
        'settings brightness',
        'settings bluetooth',
        'shop',
        'pause circle outline',
        'play arrow',
        'play circle filled',
        'play circle outline',
        'playlist add',
        'play for work',
        'picture in picture alt',
        'picture in picture',
        'pets',
        'playlist add check',
        'playlist play',
        'queue',
        'queue music',
        'queue play next',
        'not interested',
        'note',
        'pause',
        'pause circle filled',
        'dashboard',
        'credit card',
        'copyright',
        'eject',
        'donut small',
        'donut large',
        'done all',
        'done',
        'hourglass empty',
        'home',
        'favorite border',
        'favorite',
        'face',
        'extension',
        'explore',
        'exit to app',
        'event seat',
        'settings ethernet',
        'settings cell',
        'book',
        'backup',
        'autorenew',
        'assignment turned in',
        'assignment returned',
        'assignment return',
        'assignment late',
        'assignment ind',
        'grade',
        'gif',
        'get app',
        'gavel',
        'launch',
        'lightbulb outline',
        'line style',
        'line weight',
        'list',
        'perm device information',
        'alarm add',
        'alarm',
        'add shopping cart',
        'compare arrows',
        'code',
        'class',
        'chrome reader mode',
        'check circle',
        'bug report',
        'bookmark border',
        'input',
        'info outline',
        'info',
        'important devices',
        'https',
        'http',
        'hourglass full',
        'account circle',
        'account box',
        'account balance wallet',
        'account balance',
        'accessible',
        'fingerprint',
        'find replace',
        'find in page',
        'feedback',
        'invert colors',
        'label',
        'label outline',
        'language',
        'lock',
        'equalizer',
        'closed caption',
        'call to action',
        'settings input svideo',
        'settings overscan',
        'settings phone',
        'settings power',
        'settings remote',
        'history',
        'highlight off',
        'help outline',
        'help',
        'group work',
        'settings voice',
        'library music',
        'library books',
        'hearing',
        'hd',
        'games',
        'forward 5',
        'forward 30',
        'forward 10',
        'flight land',
        'flight takeoff',
        'flip to back',
        'flip to front',
        'g translate',
        'delete',
        'delete forever',
        'description',
        'dns',
        'restore',
        'report problem',
        'reorder',
        'remove shopping cart',
        'alarm off',
        'alarm on',
        'euro symbol',
        'event',
        'settings input antenna',
        'polymer',
        'power settings new',
        'pregnant woman',
        'print',
        'query builder',
        'question answer',
        'receipt',
        'record voice over',
        'redeem',
        'open in browser',
        'open in new',
        'open with',
        'pageview',
        'pan tool',
        'payment',
        'perm camera mic',
        'perm contact calendar',
        'perm data setting',
        'work',
        'youtube searched for',
        'zoom in',
        'view carousel',
        'view array',
        'view agenda',
        '3d rotation',
        'radio',
        'fiber smart record',
        'restore page',
        'room',
        'rounded corner',
        'rowing',
        'schedule',
        'view week',
        'visibility',
        'visibility off',
        'watch later',
        'shop two',
        'shopping basket',
        'shopping cart',
        'speaker notes',
        'speaker notes off',
        'spellcheck',
        'star rate',
        'stars',
        'accessibility',
        'lock open',
        'settings input hdmi',
        'settings input composite',
        'settings input component',
        'settings backup restore',
        'settings applications',
        'settings',
        'track changes',
        'view stream',
        'tab unselected',
        'tab',
        'system update alt',
        'swap vertical circle',
        'swap vert',
        'swap horiz',
        'supervisor account',
        'subject',
        'store',
        'zoom out',
        'translate',
        'trending down',
        'trending flat',
        'trending up',
        'turned in',
        'turned in not',
        'update',
        'verified user',
        'touch app',
        'toll',
        'today',
        'toc',
        'timeline',
        'thumbs up down',
        'thumb up',
        'thumb down',
        'theaters',
        'view list',
        'view headline',
        'view day',
        'view column',
        'markunread mailbox',
        'motorcycle',
        'note add',
        'offline pin',
        'opacity',
        'search',
        'add alert',
        'error',
        'error outline',
        'branding watermark',
        'av timer',
        'art track',
        'album',
        'airplay',
        'add to queue',
        'repeat',
        'remove from queue',
        'recent actors',
        'fiber pin',
        'fiber new',
        'fiber manual record',
        'high quality',
        'library add',
        'explicit',
        'fast forward',
        'fast rewind',
        'featured play list',
        'view quilt',
        'view module',
        'warning',
        'loyalty',
        'lock outline',
        'perm identity',
        'perm media',
        'perm phone msg',
        'perm scan wifi',
        'featured video',
        'fiber dvr',
        'new releases',
        'music video',
        'movie',
        'mic off',
        'mic none',
        'mic',
        'loop',
        'date range',
        'build',
        'cached',
        'camera enhance',
        'card giftcard',
        'card membership',
        'card travel',
        'change history',
        'bookmark'
      ]
    }
  }
}
</script>
